### ISSUE TITLE
[ config:import:single ] ArgumentCountError: Too few arguments

### ISSUE THREAD

**Issue by meanderix** [hechoendrupal/drupal-console#4322]
### Problem/Motivation
I used the `config:import:single` command with success in Drupal 8, but after upgrading to 9.1 I'm seeing the following error:
```
ArgumentCountError: Too few arguments to function Drupal\Core\Config\ConfigImporter::__construct(), 9 passed in /var/www/html/vendor/drupal/console/src/Command/Config/ImportSingleCommand.php on line 149 and exactly 10 expected in /var/www/html/web/core/lib/Drupal/Core/Config/ConfigImporter.php on line 194 #0 /var/www/html/vendor/drupal/console/src/Command/Config/ImportSingleCommand.php(149): Drupal\Core\Config\ConfigImporter->__construct()
#1 /var/www/html/vendor/drupal/console/src/Command/Config/ImportSingleCommand.php(121): Drupal\Console\Command\Config\ImportSingleCommand->configImport()
#2 /var/www/html/vendor/symfony/console/Command/Command.php(255): Drupal\Console\Command\Config\ImportSingleCommand->execute()
#3 /var/www/html/vendor/symfony/console/Application.php(1027): Symfony\Component\Console\Command\Command->run()
#4 /var/www/html/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#5 /var/www/html/vendor/drupal/console-core/src/Application.php(187): Symfony\Component\Console\Application->doRun()
#6 /var/www/html/vendor/drupal/console/src/Application.php(64): Drupal\Console\Core\Application->doRun()
#7 /var/www/html/vendor/symfony/console/Application.php(149): Drupal\Console\Application->doRun()
#8 /var/www/html/vendor/drupal/console/bin/drupal.php(89): Symfony\Component\Console\Application->run()
#9 /var/www/html/vendor/drupal/console/bin/drupal(4): require('/var/www/html/v...')
#10 {main}
```

### How to reproduce
`drupal config:import:single --directory="dirname" --file="custom.config.yml"`

Drupal version: 9.1.10
Console version: 1.9.7

**Comment by captnCC** [comment]
From D8 to D9 the `ConfigImporter` gained a new parameter, that isn't provided while instantiating the  class in the `configImport` method of `ImportSingleCommand`. 

Adding `\Drupal::service('extension.list.module')` as 10th parameter fixes the problem:

```php
$configImporter = new ConfigImporter(
            $storageComparer,
            \Drupal::service('event_dispatcher'),
            \Drupal::service('config.manager'),
            \Drupal::lock(),
            \Drupal::service('config.typed'),
            \Drupal::moduleHandler(),
            \Drupal::service('module_installer'),
            \Drupal::service('theme_handler'),
            \Drupal::service('string_translation'),
            \Drupal::service('extension.list.module')
        );
```

**Comment by LOBsTerr** [comment]
Should be fixed in 1.9.8
