### ISSUE TITLE
Fatal error after updating from rc18 to rc21.

### ISSUE THREAD

**Issue by cburschka-pwc** [hechoendrupal/drupal-console#3354]
After updating all three packages to 1.0.0-rc21, any command will trigger the following error:

> [Symfony\Component\Debug\Exception\FatalThrowableError]                                                                                      
  Type error: Too few arguments to function Drupal\Console\Command\Config\ExportSingleCommand::__construct(), 2 passed and exactly 3 expected

**Comment by cburschka-pwc** [comment]
I should add that deleting the `.console` folder (where the outdated service definition is cached) does not solve this error.

**Comment by cburschka-pwc** [comment]
Update: By xdebug-stepping through the bootstrap, I managed to finally track down a second `.console` folder in the home directory, which was used even after the local project's `.console` folder had been deleted.

This is really painful to troubleshoot - I suggest automatically purging the caches if the container fails to bootstrap.

**Comment by jmolivas** [comment]
I agree and will implement a cache clear deleting `.console` directory on bootstrap error.

**Comment by LOBsTerr** [comment]
@jmolivas did you do this? Can we close the issue?

**Comment by jmolivas** [comment]
@LOBsTerr yes this is gone by removing the `.console` directory. We deactivated drupal console cache for now and will re-introduce a new cache strategy in a future release.

**Comment by jmolivas** [comment]
Closing this one. Feel free to re-open if still happening after updating to the latest version.
